# ElWiz global configuration example
# Copy this file to config.yaml and adjust as needed.

# Enable/disable integrations
enableMqtt: true
enableRest: false

# MQTT settings
mqttUrl: 'mqtt://localhost:1883'
mqttOptions: {}
priceTopic: 'elwiz/prices'

# REST API settings
restPort: 3000

# Storage settings
savePath: './data'
priceFilePath: './data/prices'
currencyFilePath: './data/currencies'

# Scheduling and retention
keepDays: 7
currencyKeepDays: 7
scheduleHours: [13, 14]
scheduleMinutes: [6, 11, 16, 21]
scheduleEuMinutes: [5]
nextDayFetchHour: 13
nextDayFetchMinute: 0

# Currency source
currencyUrl: 'https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml'

# Debug
DEBUG: false
